name: Build and Upload Bottles

on:
  push:
    paths:
      - "Formula/pbctl.rb"
      - ".github/workflows/bottle.yml"
  workflow_dispatch:

jobs:
  bottle:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Setup tap directory
        run: |
          mkdir -p $(brew --repo)/Library/Taps/hakonharnes
          rm -rf $(brew --repo)/Library/Taps/hakonharnes/homebrew-tap || true
          ln -s $GITHUB_WORKSPACE $(brew --repo)/Library/Taps/hakonharnes/homebrew-tap

      - name: Build bottle
        run: |
          brew install --build-bottle hakonharnes/tap/pbctl

          # Test if it works
          echo "Testing pbctl..." 
          echo "Hello World" | pbctl
          pbctl paste || true

          # Create bottle
          brew bottle hakonharnes/tap/pbctl --root-url="https://github.com/hakonharnes/homebrew-tap/releases/download/pbctl-0.1.2"

      - name: Upload bottle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottles
          path: "*.bottle.tar.gz"
          if-no-files-found: warn

      - name: Generate bottle block
        run: |
          brew bottle --merge --write --no-commit *.bottle.json
          cp $(brew --repo)/Library/Taps/hakonharnes/homebrew-tap/Formula/pbctl.rb updated_formula.rb
          echo "Bottle block generated. Here is the updated formula:"
          cat updated_formula.rb

      - name: Upload updated formula
        uses: actions/upload-artifact@v4
        with:
          name: updated-formula
          path: updated_formula.rb
