name: build-bottles

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  bottle:
    runs-on: macos-14
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Build bottles with test-bot
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew test-bot --tap=./ \
            --only-formulae \
            --root-url="https://github.com/${{ github.repository }}/releases/download/${GITHUB_REF_NAME}"

      - name: Upload bottles to release
        uses: softprops/action-gh-release@v1
        with:
          files: bottles/*.tar.gz

      - name: Commit bottle block
        run: |
          git config user.name  "homebrew-test-bot"
          git config user.email "test-bot@users.noreply.github.com"
          cp -f bottle-formulae/*.rb Formula/
          git add Formula/pbctl.rb
          git commit -m "pbctl: add bottles for ${GITHUB_REF_NAME}" || echo "No changes"
          git push origin HEAD:${{ github.ref_name }}
