name: Build Bottles

on:
  push:
    branches: [main]
    paths:
      - 'Formula/pbctl.rb'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # ------------------------------------------------------------
  # 1. Build bottles on macOS 13, 14, and 15
  # ------------------------------------------------------------
  build-bottles:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # -----------------------------------------------------------------
      # Remove Apple-framework Python shims that break Homebrew’s linker
      # THEN install Swift 6 **without** its declared deps (python@3.13)
      # -----------------------------------------------------------------
      - name: Prepare toolchain
        run: |
          # These symlinks exist only on the macOS-13 image (Intel runner)
          sudo rm -f /usr/local/bin/{idle3*,pip3*,pydoc3*,python3*} || true
          
          # Install Swift 6, ignoring its python@3.13 dependency
          brew install --ignore-dependencies swift

      - name: Build & bottle pbctl
        env:
          # Skip the “upgrade dependents” scan (faster; avoids python again)
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          VERSION=$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' Formula/pbctl.rb | head -1)

          brew install --build-bottle Formula/pbctl.rb
          brew bottle --json \
            --root-url="https://github.com/hakonharnes/homebrew-tap/releases/download/${VERSION}" \
            pbctl

      - name: Upload bottle + JSON
        uses: actions/upload-artifact@v4
        with:
          name: pbctl-bottles-${{ matrix.os }}
          path: |
            pbctl--*.bottle.*.tar.gz
            pbctl--*.bottle.json

  # ------------------------------------------------------------
  # 2. Attach bottles to the GitHub Release (create if missing)
  # ------------------------------------------------------------
  upload-bottles:
    needs: build-bottles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bottles
        uses: actions/download-artifact@v4
        with:
          pattern: pbctl-bottles-*
          merge-multiple: true

      - name: Get version
        id: version
        run: |
          VERSION=$(grep -oP 'v\d+\.\d+\.\d+' Formula/pbctl.rb | head -1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create / update release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          FILES="pbctl--*.bottle.*.tar.gz pbctl--*.bottle.json"

          if gh release view "$VERSION" &>/dev/null; then
            gh release upload "$VERSION" $FILES --clobber
          else
            gh release create "$VERSION" \
              --title "pbctl $VERSION bottles" \
              --notes "Homebrew bottles for pbctl $VERSION" \
              $FILES
          fi

  # ------------------------------------------------------------
  # 3. Merge the bottle stanza into Formula/pbctl.rb and push
  # ------------------------------------------------------------
  merge-bottles:
    needs: upload-bottles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bottle JSONs
        uses: actions/download-artifact@v4
        with:
          pattern: pbctl-bottles-*
          merge-multiple: true

      - name: Install Homebrew (Linuxbrew) for merging
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Merge bottle block
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew bottle --merge --write --no-commit pbctl--*.bottle.json

      - name: Commit & push updated formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/pbctl.rb
          git commit -m "chore(bottles): add pbctl bottles [skip bottles]"
          git push
