name: Build Bottles

on:
  push:
    branches: [main]
    paths:
      - 'Formula/pbctl.rb'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  # ------------------------------------------------------------
  # 1. Build bottles on macOS 13, 14 and 15
  # ------------------------------------------------------------
  build-bottles:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew to latest
        run: brew update-reset -q

      - name: Prepare toolchain
        run: |
          sudo rm -f /usr/local/bin/{idle3*,pip3*,pydoc3*,python3*} || true
          brew install --ignore-dependencies swift

      - name: Build & bottle pbctl
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          VERSION=$(grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' Formula/pbctl.rb | head -1)

          brew install --build-bottle Formula/pbctl.rb
          brew bottle --json \
            --root-url="https://github.com/hakonharnes/homebrew-tap/releases/download/${VERSION}" \
            pbctl

          for f in pbctl--*.bottle.*; do
            mv "$f" "$(echo "$f" | sed 's/pbctl--/pbctl-/')"
          done

      - name: Upload bottle + JSON
        uses: actions/upload-artifact@v4
        with:
          name: pbctl-bottles-${{ matrix.os }}
          path: |
            pbctl*.bottle.*.tar.gz
            pbctl*.bottle.json

  # ------------------------------------------------------------
  # 2. Attach bottles to the GitHub Release
  # ------------------------------------------------------------
  upload-bottles:
    needs: build-bottles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bottles
        uses: actions/download-artifact@v4
        with:
          pattern: pbctl-bottles-*
          merge-multiple: true

      - name: Get version
        id: version
        run: |
          VERSION=$(grep -oP 'v\d+\.\d+\.\d+' Formula/pbctl.rb | head -1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create / update release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          FILES="pbctl*.bottle.*.tar.gz pbctl*.bottle.json"

          if gh release view "$VERSION" &>/dev/null; then
            gh release upload "$VERSION" $FILES --clobber
          else
            gh release create "$VERSION" \
              --title "pbctl $VERSION bottles" \
              --notes "Homebrew bottles for pbctl $VERSION" \
              $FILES
          fi

  # ------------------------------------------------------------
  # 3. Merge the bottle stanza into the formula and push
  # ------------------------------------------------------------
  merge-bottles:
    needs: upload-bottles
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download bottle JSONs
        uses: actions/download-artifact@v4
        with:
          pattern: pbctl-bottles-*
          merge-multiple: true

      - name: Install Homebrew (Linuxbrew) for merging
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Tap local repo
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap hakonharnes/tap "$(pwd)"

      - name: Merge bottle block
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew bottle --merge --write --no-commit pbctl*.bottle.json
          TAP_PATH=$(brew --repository hakonharnes/tap)
          cp "$TAP_PATH/Formula/pbctl.rb" Formula/pbctl.rb

      - name: Commit & push updated formula
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add Formula/pbctl.rb
          if git diff --cached --quiet; then
            echo "Formula already up-to-date — nothing to commit"
            exit 0
          fi

          git commit -m "chore(bottles): add pbctl bottles [skip bottles]"
          git push
