name: Check for Updates

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for pbctl updates
        run: |
          echo "=== Checking for pbctl updates ==="
          
          # Get latest release from pbctl repo
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hakonharnes/pbctl/releases/latest | jq -r .tag_name)
          echo "Latest version available: $LATEST_VERSION"
          
          # Get current version from formula
          CURRENT_VERSION=$(grep -oP 'v\d+\.\d+\.\d+' Formula/pbctl.rb | head -1)
          echo "Current version in formula: $CURRENT_VERSION"
          
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo ""
            echo "🚨 UPDATE NEEDED!"
            echo "==================="
            echo "Current: $CURRENT_VERSION"
            echo "Latest:  $LATEST_VERSION"
            echo ""
            
            # Calculate new SHA256
            curl -L "https://github.com/hakonharnes/pbctl/archive/refs/tags/${LATEST_VERSION}.tar.gz" -o pbctl.tar.gz
            SHA256=$(sha256sum pbctl.tar.gz | cut -d' ' -f1)
            echo "New SHA256: $SHA256"
            echo ""
            echo "To update, change Formula/pbctl.rb:"
            echo "- URL: https://github.com/hakonharnes/pbctl/archive/refs/tags/${LATEST_VERSION}.tar.gz"
            echo "- SHA256: $SHA256"
            echo "- Version in test: ${LATEST_VERSION#v}"
          else
            echo ""
            echo "✅ Formula is up to date!"
          fi