name: brew pr-pull

on:
  pull_request_target:
    types: [labeled]

jobs:
  pr-upload:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Download built bottles
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Upload & merge
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN || github.token }}
        run: |
          brew pr-pull --tap="$GITHUB_REPOSITORY"
