name: brew test-bot

on:
  pull_request:
    paths:
      - "Formula/**"
  workflow_dispatch:

jobs:
  matrix-test:
    strategy:
      matrix:
        os: [macos-12, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN || github.token }}
        run: |
          brew test-bot --tap="$GITHUB_REPOSITORY" --only-formulae --tap-new-commit
