name: Test Update Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test update check
        run: |
          echo "Testing update check logic..."
          
          # Get latest release from pbctl repo
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hakonharnes/pbctl/releases/latest | jq -r .tag_name)
          echo "Latest version from GitHub: $LATEST_VERSION"
          
          # Get current version from formula
          CURRENT_VERSION=$(grep -oP 'v\d+\.\d+\.\d+' Formula/pbctl.rb | head -1)
          echo "Current version in formula: $CURRENT_VERSION"
          
          # Compare versions
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Update needed! $CURRENT_VERSION -> $LATEST_VERSION"
          else
            echo "Formula is up to date"
          fi
          
          # Test SHA256 calculation
          echo "Testing SHA256 calculation..."
          curl -L "https://github.com/hakonharnes/pbctl/archive/refs/tags/${CURRENT_VERSION}.tar.gz" -o pbctl-test.tar.gz
          SHA256=$(sha256sum pbctl-test.tar.gz | cut -d' ' -f1)
          echo "Calculated SHA256: $SHA256"
          
          # Verify against formula
          FORMULA_SHA256=$(grep -oP 'sha256\s+"\K[a-f0-9]+' Formula/pbctl.rb)
          echo "Formula SHA256: $FORMULA_SHA256"
          
          if [ "$SHA256" = "$FORMULA_SHA256" ]; then
            echo "SHA256 verification passed!"
          else
            echo "SHA256 mismatch!"
            exit 1
          fi